package main

var excuses = []string{
	"excuse me waiter, there's a 404 in my link",
	"404 outlook not so good",
	"do you like pina coladas, and getting FILE NOT FOUND?",
	"always, I know, you'll be, 404",
	"it's a bittersweet symphony, this 404",
	"hey now, you're a rockstar, get the show on, 404",
	"sorry girl, but you missed out, well tough luck that 404's now",
	"music hits me, so hard, makes me say, 404",
	"i'm blue, 404044, 404, 404, 404044 (4 4 4..)",
	"if you wanna be my lover, you gotta 404 my friends",
	"if I 404 will you still call me superman?",
	"oops I did it again",
	"you better lose yourself in the music, the moment, you hold it, you better never 404",
	"i feel stupid, and contagious, 404 now, imitate us",
}

var fragments = []string{
	"abc",
	"age",
	"any",
	"are",
	"bad",
	"bag",
	"bar",
	"bud",
	"bun",
	"bus",
	"buy",
	"cab",
	"can",
	"cow",
	"cuz",
	"dis",
	"doc",
	"dub",
	"eww",
	"fix",
	"foo",
	"fox",
	"fry",
	"got",
	"grr",
	"hey",
	"hip",
	"hit",
	"ikr",
	"joy",
	"key",
	"lol",
	"luv",
	"map",
	"msg",
	"mug",
	"nod",
	"not",
	"off",
	"pay",
	"peg",
	"pho",
	"pun",
	"red",
	"say",
	"soy",
	"sry",
	"sun",
	"the",
	"top",
	"try",
	"two",
	"txt",
	"uni",
	"van",
	"vim",
	"was",
	"who",
	"wow",
	"wut",
	"xyz",
	"yes",
}
