version: "2"
services:
  shortlink:
    build: .
    environment:
      POSTGRES_URI: postgres://root@postgres/shortlink
      SHORTLINK_LISTEN_ADDR: ":8000"
      HEALTHCHECK_LISTEN_ADDR: ":9000"
      BASE_URL: "http://localhost:8000/"
    depends_on: 
      - postgres
    ports:
      - "8000:8000"
      - "9000:9000"
  postgres:
    image: postgres:latest
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
